all: factorise_3_0_a factorise_3_0_b factorise_3_0_c factorise_3_0_d factorise_3_0_e

factorise_3_0_a: factorise_3_0_a.c
	cc -o factorise_3_0_a factorise_3_0_a.c

factorise_3_0_b: factorise_3_0_b.c
	cc -o factorise_3_0_b factorise_3_0_b.c

factorise_3_0_c: factorise_3_0_c.c
	cc -o factorise_3_0_c factorise_3_0_c.c

factorise_3_0_d: factorise_3_0_d.c
	cc -o factorise_3_0_d factorise_3_0_d.c

factorise_3_0_e: factorise_3_0_e.c
	cc -o factorise_3_0_e factorise_3_0_e.c

clean:
	rm -f a.out *~ factorise_3_0_a factorise_3_0_b factorise_3_0_c factorise_3_0_d factorise_3_0_e


