all: multiply0 multiply1 multiply2 multiply3 multiply4

multiply0: multiply0.c
	cc -o multiply0 multiply0.c -pthread	       

multiply1: multiply1.c
	cc -o multiply1 multiply1.c -pthread	       

multiply2: multiply2.c
	cc -o multiply2 multiply2.c -pthread	       

multiply3: multiply3.c
	cc -o multiply3 multiply3.c -pthread	       

multiply4: multiply4.c
	cc -o multiply4 multiply4.c -pthread	       

clean: 
	rm -f a.out *~ multiply0 multiply1 multiply2 multiply3 

